package com.youranxue.domain.mapper;

import com.youranxue.domain.model.BookMst;
import com.youranxue.domain.model.BookMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int countByExample(BookMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int deleteByExample(BookMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int deleteByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int insert(BookMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int insertSelective(BookMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    List<BookMst> selectByExample(BookMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    BookMst selectByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookMst record, @Param("example") BookMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int updateByExample(@Param("record") BookMst record, @Param("example") BookMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int updateByPrimaryKeySelective(BookMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.book_mst
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    int updateByPrimaryKey(BookMst record);
}