package com.youranxue.domain.mapper;

import com.youranxue.domain.model.GradeMst;
import com.youranxue.domain.model.GradeMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GradeMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int countByExample(GradeMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int deleteByExample(GradeMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int deleteByPrimaryKey(Integer gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int insert(GradeMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int insertSelective(GradeMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    List<GradeMst> selectByExample(GradeMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    GradeMst selectByPrimaryKey(Integer gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") GradeMst record, @Param("example") GradeMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int updateByExample(@Param("record") GradeMst record, @Param("example") GradeMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int updateByPrimaryKeySelective(GradeMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.grade_mst
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    int updateByPrimaryKey(GradeMst record);
}