package com.youranxue.domain.model;

public class BookMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.book_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.grade_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.book_name
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.isbn
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.subject_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.semester_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private Integer semesterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.publisher_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private Integer publisherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.book_mst.user_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.book_id
     *
     * @return the value of youranxue.book_mst.book_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.book_id
     *
     * @param bookId the value for youranxue.book_mst.book_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.grade_id
     *
     * @return the value of youranxue.book_mst.grade_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.grade_id
     *
     * @param gradeId the value for youranxue.book_mst.grade_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.book_name
     *
     * @return the value of youranxue.book_mst.book_name
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.book_name
     *
     * @param bookName the value for youranxue.book_mst.book_name
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.isbn
     *
     * @return the value of youranxue.book_mst.isbn
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.isbn
     *
     * @param isbn the value for youranxue.book_mst.isbn
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.subject_id
     *
     * @return the value of youranxue.book_mst.subject_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.subject_id
     *
     * @param subjectId the value for youranxue.book_mst.subject_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.semester_id
     *
     * @return the value of youranxue.book_mst.semester_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public Integer getSemesterId() {
        return semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.semester_id
     *
     * @param semesterId the value for youranxue.book_mst.semester_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.publisher_id
     *
     * @return the value of youranxue.book_mst.publisher_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public Integer getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.publisher_id
     *
     * @param publisherId the value for youranxue.book_mst.publisher_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setPublisherId(Integer publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.book_mst.user_id
     *
     * @return the value of youranxue.book_mst.user_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.book_mst.user_id
     *
     * @param userId the value for youranxue.book_mst.user_id
     *
     * @mbggenerated Sun Oct 29 16:15:19 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}