package com.youranxue.domain.model;

public class ChapterMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.chapter_mst.chapter_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private Integer chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.chapter_mst.chapter_name
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private String chapterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.chapter_mst.book_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.chapter_mst.grade_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private Integer gradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.chapter_mst.chapter_id
     *
     * @return the value of youranxue.chapter_mst.chapter_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.chapter_mst.chapter_id
     *
     * @param chapterId the value for youranxue.chapter_mst.chapter_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.chapter_mst.chapter_name
     *
     * @return the value of youranxue.chapter_mst.chapter_name
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.chapter_mst.chapter_name
     *
     * @param chapterName the value for youranxue.chapter_mst.chapter_name
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.chapter_mst.book_id
     *
     * @return the value of youranxue.chapter_mst.book_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.chapter_mst.book_id
     *
     * @param bookId the value for youranxue.chapter_mst.book_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.chapter_mst.grade_id
     *
     * @return the value of youranxue.chapter_mst.grade_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.chapter_mst.grade_id
     *
     * @param gradeId the value for youranxue.chapter_mst.grade_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
}