package com.youranxue.domain.model;

public class GradeMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.grade_mst.grade_id
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.grade_mst.grade_name
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    private String gradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.grade_mst.publisher_id
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    private Integer publisherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.grade_mst.grade_id
     *
     * @return the value of youranxue.grade_mst.grade_id
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.grade_mst.grade_id
     *
     * @param gradeId the value for youranxue.grade_mst.grade_id
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.grade_mst.grade_name
     *
     * @return the value of youranxue.grade_mst.grade_name
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.grade_mst.grade_name
     *
     * @param gradeName the value for youranxue.grade_mst.grade_name
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.grade_mst.publisher_id
     *
     * @return the value of youranxue.grade_mst.publisher_id
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    public Integer getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.grade_mst.publisher_id
     *
     * @param publisherId the value for youranxue.grade_mst.publisher_id
     *
     * @mbggenerated Wed Oct 18 10:35:18 CST 2017
     */
    public void setPublisherId(Integer publisherId) {
        this.publisherId = publisherId;
    }
}