package com.youranxue.domain.model;

public class PublisherMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.publisher_mst.publisher_id
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    private Integer publisherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.publisher_mst.publisher_name
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    private String publisherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.publisher_mst.book_id
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.publisher_mst.publisher_id
     *
     * @return the value of youranxue.publisher_mst.publisher_id
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    public Integer getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.publisher_mst.publisher_id
     *
     * @param publisherId the value for youranxue.publisher_mst.publisher_id
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    public void setPublisherId(Integer publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.publisher_mst.publisher_name
     *
     * @return the value of youranxue.publisher_mst.publisher_name
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.publisher_mst.publisher_name
     *
     * @param publisherName the value for youranxue.publisher_mst.publisher_name
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.publisher_mst.book_id
     *
     * @return the value of youranxue.publisher_mst.book_id
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.publisher_mst.book_id
     *
     * @param bookId the value for youranxue.publisher_mst.book_id
     *
     * @mbggenerated Sun Oct 29 15:04:33 CST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}