package com.youranxue.domain.model;

public class SectionMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.section_mst.section_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.section_mst.chapter_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private Integer chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.section_mst.section_name
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private String sectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.section_mst.knowledge_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    private Integer knowledgeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.section_mst.section_id
     *
     * @return the value of youranxue.section_mst.section_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.section_mst.section_id
     *
     * @param sectionId the value for youranxue.section_mst.section_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.section_mst.chapter_id
     *
     * @return the value of youranxue.section_mst.chapter_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.section_mst.chapter_id
     *
     * @param chapterId the value for youranxue.section_mst.chapter_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.section_mst.section_name
     *
     * @return the value of youranxue.section_mst.section_name
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.section_mst.section_name
     *
     * @param sectionName the value for youranxue.section_mst.section_name
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.section_mst.knowledge_id
     *
     * @return the value of youranxue.section_mst.knowledge_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public Integer getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.section_mst.knowledge_id
     *
     * @param knowledgeId the value for youranxue.section_mst.knowledge_id
     *
     * @mbggenerated Sun Oct 29 16:13:36 CST 2017
     */
    public void setKnowledgeId(Integer knowledgeId) {
        this.knowledgeId = knowledgeId;
    }
}